version: '3.7'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq1
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 15671:15671
    - 15672:15672
    - 25672:25672
    networks:
    - cluster-network

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
    - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq2
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
    - 4469:4369
    - 5771:5671
    - 5772:5672
    - 16671:15671
    - 16672:15672
    - 26672:25672
    networks:
    - cluster-network

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    depends_on:
    - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq3
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
    - 4569:4369
    - 5871:5671
    - 5872:5672
    - 17671:15671
    - 17672:15672
    - 27672:25672
    networks:
    - cluster-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: producer
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_HOST1: rabbitmq1
      RABBITMQ_PORT1: 5672
      RABBITMQ_HOST2: rabbitmq2
      RABBITMQ_PORT2: 5672
      RABBITMQ_HOST3: rabbitmq3
      RABBITMQ_PORT3: 5672
    ports:
      - 8081:8081
    networks:
    - cluster-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: consumer
    depends_on:
      - rabbitmq1
    environment:
      RABBITMQ_HOST1: rabbitmq1
      RABBITMQ_PORT1: 5672
      RABBITMQ_HOST2: rabbitmq2
      RABBITMQ_PORT2: 5672
      RABBITMQ_HOST3: rabbitmq3
      RABBITMQ_PORT3: 5672
    ports:
      - 8082:8082
    networks:
    - cluster-network

networks:
  cluster-network:
    driver: bridge