version: '3.7'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq1
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "15671:15671"
    - "15672:15672"
    - "25672:25672"
    networks:
    - cluster-network

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
    - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq2
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    networks:
    - cluster-network

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    depends_on:
    - rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq-cluster-secret
      RABBITMQ_NODENAME: rabbitmq3
    volumes:
    - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    - "./definitions.json:/etc/rabbitmq/definitions.json"
    networks:
    - cluster-network

networks:
  cluster-network:
    driver: bridge